const quotes = [ 
"Stop being sus.",
"I said shut up.",
"Can you be quiet?",
"I don’t care! I didn’t ask either.",
"You’re disrupting the class, I don’t appreciate it.",
"Shut up and listen.",
"I sleep great at night, after I said that.",
"Too much information, stop it!",
"Can the rest of you shut up?",
"Tell someone who cares.", //10
"Fahad KHAN you shut up?",
"Mediocre, just like your test.",
"Nobody looks at math and smiles",
"*Disappointed sigh*",
"I have said shut up in class",
"You foiled my artwork",
"Just stop capping",
"Oh sorry, you’re not year 7s, you’re 7-year-olds",
"That's BS",
"Are you sure about that?",
"I have been waiting.",
"Who asked?",
"What happened to shutting up?",
"#WhendidIask",
"You do, and always will, need help.",
"Are you calling me a bully? Takes one to know one",
"When did I ask?",
"I foiled your plan",
"Do your revision now!",
"Do thy revision now! Thus sayeth Ang!",
"Another day, another slay",
"请你闭嘴。",
"I mean you might be thinking of men all the time, but that's not it",
"Bro??",
"If I could play the cricket chirping sound, I would",
"What the heck-tare?!",
"No, he’s the punchline",
"Hey, don’t complain.",
"You behave like 7-year-olds",
"Bruv, shut up",
"Sit down and slay the day away",
"Takes one to know one",
"Whats the roundest knight on the table? Circumference",
"I’m glad I learned sign language, it's pretty handy!",
"Don’t be rash, do your work.",
"Har har har.",
"I stayed up all night wondering where the sun went, then it dawned on me.",
"I’ve forgotten how to throw a boomerang, then it came back to me.",
"Get out your journals",
"OoOoOo Waleed and Renee ❤",
"Not everyone is like you",
"I’m not Muslim, I can’t have 4 wives",
"Are you guys dads?",
"I liked the pun",
"Soumil I think the water is running for you",
"You foiled my plan",
"Tape your mouth up!",
"What do you call a fish thats made of 2 sodium atoms? 2na, like tuna!",
"But when- DID I ASK! OOOOOH",
"Guys!",
"Why, do you not have one?",
"Stop talking - STOP TALKING",
"CD’s???!",
"欠打？",
"Who? ASKED",
"What is a four letter word used to describe women, that ends in -unt? Aunt",
"Did you want moeed to call you daddy?",
"Are you being rash-ist?",
"Ian’s phone and Soumil’s watch are both dirty in different ways",
"The horse used to drive the cart, but now the cart drives the horse. How the stables have turned",
"You sound like you’re enjoying it",
"Yushi, you pastry",
"Shoulda gone to specsavers",
"Cry me a river",
"My observation is that you can’t shut up for long enough",
"Time is passing, are you?",
"Smh",
"Joe. Joe mama",
"Well mode’s the most common one",
"Can you stop being a dog?", //80
"Stawwwp it!",
"Casper you better make sure you do good in school or else you won’t get any boobies",
"Speaking to NOBODY IN PARTICULAR *stares at Renee*",
"That was so 2015",
"I will mentally mark your work",
"And my 800 math students will know what to do when someone is talking",
"Shut up and listen, and I mean the shut up part",
"You played it and you blamed it on Zane, that’s a dog move",
"You're 134? What’s your skin care routine?",
"You’re being sarcastic so I’m being sarcastic back at you", //90
"Believe me, there's so many students I would like to hit",
"Well sucks to be you",
"An A-grade student should know how to sight read",
"Josiah! You're not fixing strings, you're breaking them",
"I'll put Renee in between Andleeb and Waleed: It could be a love triangle",
"Why are ignite kids so mean? Because they're so average",
"Are you the reason their relationship lasted 26hrs?",
"Rashmi just had to respond to you",
"Maybe there’s something else going on in the house",
"*Flips of kid while scratching ear and while pushing up glasses*", //100!!
"Stop farting",
"Can you stop with that elitist behaviour? I am better than you.",
"Old man Bruce",
"Typical violin 1",
"You can't have everything you want",
"Arya serious?",
"Renee are you a terrorist?",
"Of course you know",
"Are you going to a volleyball match or a drag show?",
"Lucky he didn't call you eshay", //110
"No wonder you got rejected",
"How can I break your heart when you're sitting next to the love of your life?",
"After all the attention I give you, this is how you treat me?",
"I'm allergic to your BS",
"Cow feces",
"I smell CF from your table",
"Do you need your bottle now? Is it feeding time?",
"BS",
"Oh dear",
"*Dies from laughing*", //120
"There's no space cos you already have someone else?",
"Cap.",
"Hi bored, I'm Mr Ang",
"You wouldn't shut up, but when Renee comes to the front you shut up",
"Eshay",
"Stop talking CRAP, get on with it",
"It's not always good to finish first",
"Why can't you keep your hands off Renee?",
"I'm not your bruh, I'm yout teacher",
"Renee you jealous?", //130
"*Shakes head disapprovingly*",
"Keep it in your pants",
"Yeah, says you",
"That sounds like a 'U' problem!",
"Ishan fell for Renee",
"Can you shut the front door?",
"It's not a room issue, its a skill issue",
"Well, gg",
"Stop being a smart donkey",
"Waleed I don’t think what you do with Renee is being halal", //140
"The real Mr Ang, was the Mr Ang we made along the way"
];
