var quotes = [ 
"Just stop capping!",
"I have said shut up in class.",
"I foiled your plan",
"If you don't follow my instructions why should I follow yours?\"<br>- Ang</p>", 
"*Disappointed sigh*", 
"Mediocre. Just like your test.", 
"Stop being such a smartass.",
"When did I ask?",
"Who asked?",
"That's BS.", //10
"Nobody looks at  math and smiles.",
"Are you calling me a bully? Takes one to know one.",
"You foiled my artwork.",
"Stop being sus.",
"Too much information! Stop it!",
"Takes one to know one.",
"I don't care. I didn't ask either.",
"You're disrupting the class. I don't appreciate it.",
"Shut up and listen.",
"Are you sure about that?", //20
"Do your revision now!",
"You do, and always will, need help.",
"Fahad KHAN you shut up?",
"Tell someone who cares.",
"I have been waiting.",
"#WhenDidIAsk?",
"I sleep great at night, after I said that.",
"What happened to shutting up?",
"You do, and always will, need help.",
"“Do thy revision now!” Thus sayeth Ang!", //30
"Oh sorry, you’re not year 7s, you're 7 year olds.",
"You behave like 7 year olds.",
"Hey, don’t complain.",
"请你闭嘴。",
"I’m glad I learned sign language, it's pretty handy!",
"I mean you might be thinking of men all the time, but thats not it",
"Whats the roundest knight on the table? Circumference",
"What the heck-tare?!",
"If I could play the cricket chirping sound, I would",
"Sit down and slay the day away", //40
"No, he’s the punchline",
"Bruv, shut up",
"Bro??",
"Tape your mouth up!",
"Another day, another slay."
"#ListenToTheTeacher",
"I will mentally mark your work",
];
